[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
files = ["stackinator/", "unittests/"]
exclude = "stackinator/repo/packages/"
ignore_missing_imports = true
check_untyped_defs = true

[tool.isort]
 profile = "black"
 skip = ["external/"]
